name: Code Changes

on:
  pull_request:
    types:
      - opened
      - labeled
    branches:
      - repo-sync
  workflow_dispatch:

jobs:
  code-changes:
    if: contains(github.event.pull_request.labels.*.name, 'repo-sync-automated')
    runs-on: ubuntu-latest
    env:
      TargetRepo: repo-sync
    steps:
      - name: Checkout ${{ env.TargetRepo }} branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TargetRepo }}

      - name: Get latest tivo/actions-runner release
        run: |
          echo "GH_RUNNER_VERSION=$(curl -sL https://api.github.com/repos/tivo/actions-runner/releases/latest | jq -r .tag_name | cut -c2-)" >> $GITHUB_ENV

      - name: Replace Jenkinsfile runner version
        run: |
          git fetch
          git checkout origin/tivo-build -- Jenkinsfile
          sed -i "s/imageVersion = .*$/imageVersion = '${{ env.GH_RUNNER_VERSION }}'/" ./Jenkinsfile

      - name: Commit changes to ${{ env.TargetRepo }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] apply runner version to Jenkinsfile"
          add: '["./Jenkinsfile"]'
