name: Repo Sync

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      pr_destination_branch:
        type: choice
        description: Destination branch
        options:
          - master
          - "tivo-build"

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    env:
      PRDestinationBranch: ${{ github.event_name == 'schedule' && 'tivo-build' || github.event.inputs.pr_destination_branch }}
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: ${{ secrets.REPO_SYNC_SOURCE_REPO }}
          source_branch: master
          destination_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
      - uses: repo-sync/pull-request@v2
        name: Create pull request
        with:
          source_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          destination_branch: ${{ env.PRDestinationBranch }}
          pr_title: "[Automated] ${{ github.ref }} into ${{ env.PRDestinationBranch }}"
          pr_label: "repo-sync-automated"
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
