name: Repo Sync

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
env:
  PR_DESTINATION_BRANCH: 'tivo-build'

jobs:
  compare-runner-versions:
    name: Compare tivo/docker-github-actions-runner and myoung34/docker-github-actions-runner release compare-runner-versions
    runs-on: ubuntu-latest
    outputs:
      runner_version_mismatch: ${{ steps.compare_runner_versions.outputs.runner_version_mismatch }}
      runner_version_upstream: ${{ steps.get_upstream_ver.outputs.runner_version }}
      runner_version_tivo: ${{ steps.get_tivo_ver.outputs.runner_version }}
    steps:
      - name: Get version number of latest myoung34/docker-github-actions-runner release
        id: get_upstream_ver
        run: |
          UPSTREAM_VER=$(curl -sL https://api.github.com/repos/myoung34/docker-github-actions-runner/releases/latest | jq -r .tag_name)
          echo "gh_runner_version_upstream=$UPSTREAM_VER" >> $GITHUB_ENV
          echo "runner_version=$UPSTREAM_VER" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Get version number of latest tivo/actions-runner release
        id: get_tivo_ver
        run: |
          git fetch
          git checkout origin/tivo-build -- runnerVersion
          TIVO_VER=$(cat runnerVersion)
          echo "gh_runner_version_tivo=$TIVO_VER" >> $GITHUB_ENV
          echo "runner_version=$TIVO_VER" >> $GITHUB_OUTPUT
      - name: Compare release versions
        id: compare_runner_versions
        run: |
          [[ "${{ env.gh_runner_version_upstream }}" != "${{ env.gh_runner_version_tivo }}" ]] \
          && echo "runner_version_mismatch=true" >> $GITHUB_OUTPUT \
          || echo "runner_version_mismatch=false" >> $GITHUB_OUTPUT

  repo-sync:
    name: "Sync upstream changes to tivo-build branch"
    if: needs.compare-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: compare-runner-versions
    runs-on: ubuntu-latest
    env:
      gh_runner_version_mismatch: ${{ needs.compare-runner-versions.outputs.runner_version_mismatch }}
      gh_runner_version_upstream: ${{ needs.compare-runner-versions.outputs.runner_version_upstream }}
      gh_runner_version_tivo: ${{ needs.compare-runner-versions.outputs.runner_version_tivo }}
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
      - name: Sync repo to branch
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ secrets.REPO_SYNC_SOURCE_REPO }}
          source_branch: v${{ env.gh_runner_version_upstream }}
          destination_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
      # - uses: repo-sync/pull-request@v2
      # use fix-diff version because of HTTP 422 errors
      # https://github.com/repo-sync/pull-request/issues/119
      - name: Create pull request
        uses: repo-sync/pull-request@fix-diff
        with:
          source_branch: ${{ secrets.REPO_SYNC_INTERMEDIATE_BRANCH }}
          destination_branch: ${{ env.PR_DESTINATION_BRANCH }}
          pr_title: "[Automated] ${{ github.ref }} into ${{ env.PR_DESTINATION_BRANCH }}"
          pr_label: "repo-sync-automated"
          pr_allow_empty: true
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}

  code-changes:
    name: "Code changes"
    if: needs.compare-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: [compare-runner-versions, repo-sync]
    runs-on: ubuntu-latest
    env:
      TargetBranch: repo-sync
      gh_runner_version_upstream: ${{ needs.compare-runner-versions.outputs.runner_version_upstream }}
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TargetBranch }}
      - name: Update runnerVersion file
        run: |
          git fetch
          cat "$gh_runner_version_upstream" >> ./runnerVersion
      - name: Commit changes to ${{ env.TargetBranch }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] update runner version"
          add: '["./runnerVersion"]'
