name: Repo Sync

on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:
    
env:
  DESTINATION_BRANCH: 'tivo-build'

jobs:
  compare-runner-versions:
    name: Compare "./runnerVersion" and "myoung34/docker-github-actions-runner" release versions
    runs-on: ubuntu-latest
    outputs:
      runner_version_mismatch: ${{ steps.compare_runner_versions.outputs.runner_version_mismatch }}
      runner_version_upstream: ${{ steps.get_upstream_release_version.outputs.runner_version }}
      runner_version_local: ${{ steps.get_local_release_version.outputs.runner_version }}
    steps:
      - name: Get version number of latest myoung34/docker-github-actions-runner release
        id: get_upstream_release_version
        run: |
          UPSTREAM_VER=$(curl -sL https://api.github.com/repos/myoung34/docker-github-actions-runner/releases/latest | jq -r .tag_name)
          echo "gh_runner_version_upstream=$UPSTREAM_VER" >> $GITHUB_ENV
          echo "runner_version=$UPSTREAM_VER" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Get version number of latest tivo/actions-runner release
        id: get_local_release_version
        run: |
          git fetch
          git checkout origin/tivo-build -- runnerVersion
          TIVO_VER=$(cat runnerVersion)
          echo "gh_runner_version_tivo=$TIVO_VER" >> $GITHUB_ENV
          echo "runner_version=$TIVO_VER" >> $GITHUB_OUTPUT
      - name: Compare release versions
        id: compare_runner_versions
        run: |
          [[ "${{ env.gh_runner_version_upstream }}" != "${{ env.gh_runner_version_tivo }}" ]] \
          && echo "runner_version_mismatch=true" >> $GITHUB_OUTPUT \
          || echo "runner_version_mismatch=false" >> $GITHUB_OUTPUT

  repo-sync:
    name: "Sync upstream changes to tivo-build branch"
    if: needs.compare-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: compare-runner-versions
    runs-on: ubuntu-latest
    env:
      gh_runner_version_mismatch: ${{ needs.compare-runner-versions.outputs.runner_version_mismatch }}
      gh_runner_version_upstream: ${{ needs.compare-runner-versions.outputs.runner_version_upstream }}
      gh_runner_version_local: ${{ needs.compare-runner-versions.outputs.runner_version_local }}
      upstream_repo: "myoung34/docker-github-actions-runner"
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DESTINATION_BRANCH }}
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: ${{ env.DESTINATION_BRANCH }}
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: v${{ env.gh_runner_version_upstream }}
          upstream_sync_repo: ${{ env.upstream_repo }}
          upstream_repo_access_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs' # overwrite everything in tivo-build branch
          test_mode: false

  code-changes:
    name: "Code changes"
    if: needs.compare-runner-versions.outputs.runner_version_mismatch == 'true'
    needs: [compare-runner-versions, repo-sync]
    runs-on: ubuntu-latest
    env:
      gh_runner_version_upstream: ${{ needs.compare-runner-versions.outputs.runner_version_upstream }}
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.DESTINATION_BRANCH }}
      - name: Update runnerVersion file
        run: |
          git fetch
          cat "$gh_runner_version_upstream" >> ./runnerVersion
      - name: Commit changes to ${{ env.DESTINATION_BRANCH }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Automated] update runner version"
          add: '["./runnerVersion"]'
