name: Repo Sync

on:
  # schedule:
  #   - cron: "*/15 * * * *" # every 15 minutes. set to whatever interval you like
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/github-sync@v2
        name: Sync repo to branch
        with:
          source_repo: ${{ secrets.REPO_SYNC_SOURCE_REPO }}
          source_branch: main
          destination_branch: ${{ secrets.FORK_SYNC_INTERMEDIATE_BRANCH }}
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
      - uses: repo-sync/pull-request@v2
        name: Create pull request
        with:
          source_branch: ${{ secrets.FORK_SYNC_INTERMEDIATE_BRANCH }}
          destination_branch: main
          pr_title: "[Automated] ${{ github.ref }} into main"
          github_token: ${{ secrets.TIVOBOT_GITHUB_ACTION_TOKEN }}
