on:
  pull_request:

name: "Trigger: Push action"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
